### ISSUE TITLE
Won't work using minishift boot2docker [default] image

### ISSUE THREAD

**Issue by ffirg** [rlucente-se-jboss/resilient-network-demo#1]
That's not RHEL based so the subscription-manager commands aren't applicable. 

$ minishift version
minishift v1.7.0+1549135

$ minishift ssh
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec
docker@minishift:~$ uname -a
Linux minishift 4.4.27-boot2docker #1 SMP Tue Oct 25 19:51:49 UTC 2016 x86_64 GNU/Linux

**Comment by rlucente-retro** [comment]
Thanks for the report.  In the README I specifically direct folks to the Red Hat Developer Program's Container Development Kit (CDK) at https://developers.redhat.com/products/cdk/download/  After signing up for a free account, you'll have access to the CDK.  Download the latest version and rename it minishift.  All of the commands in the README will then work.

**Comment by rlucente-retro** [comment]
I'm going to close this issue as my intent was to direct this project to the supported enterprise bits using the CDK.
