### ISSUE TITLE
minishift setup-cdk is not a valid command in latest version

### ISSUE THREAD

**Issue by ffirg** [rlucente-se-jboss/resilient-network-demo#2]
$ minishift version
minishift v1.7.0+1549135

$ minishift setup-cdk
Error: unknown command "setup-cdk" for "minishift"
Run 'minishift --help' for usage.
unknown command "setup-cdk" for "minishift"

**Comment by rlucente-retro** [comment]
Thanks for the report.  In the README I specifically direct folks to the Red Hat Developer Program's Container Development Kit (CDK) at https://developers.redhat.com/products/cdk/download/  After signing up for a free account, you'll have access to the CDK.  Download the latest version and rename it minishift.  All of the commands in the README will then work.  This includes setup-cdk which creates a directory in $HOME/.minishift that contains various files and configuration settings.

**Comment by rlucente-retro** [comment]
I'm going to close this issue as my intent was to direct this project to the supported enterprise bits using the CDK.

**Comment by ffirg** [comment]
I’d suggest a note about using the ‘other’ minishift, as although you’ve pointed out the CDK, if someone (like me) is already using mini shift, it looks like it should work.
BTW, I’m just downloading the centos iso image and will try that. That replaces boot2docker as the default.

I also already have a .minishift config and have it setup to restrict resources on my Mac.

**Comment by rlucente-se-jboss** [comment]
Ok.  I'll add a note up front and let folks know this is the
developer.redhat.com minishift.

Rich Lucente

Senior Specialist Solution Architect

Red Hat Public Sector
<https://www.redhat.com>

rlucente@redhat.com    M: 240-994-0562
<https://red.ht/sig>
TRIED. TESTED. TRUSTED. <https://redhat.com/trusted>

**Comment by rlucente-retro** [comment]
Ok, I'll add a note up front that this is the developer.redhat.com version of minishift.

**Comment by ffirg** [comment]
When you say rename it to mini shift, what are you referring to?
I’ve installed via the Dev Suite installer btw

**Comment by rlucente-retro** [comment]
If you download cdk-3.1.1-1-minishift-darwin-amd64 then you rename that
file to minishift.

**Comment by ffirg** [comment]
If you download using the dev suite installer, it looks like it symlinks /usr/local/bin/minishift to /Applications/… on the Mc.
This confused me as I already had a /usr/local/bin/minishift which I then overwrote back to my original!

I’m getting docker registry push errors now which is strange :(

**Comment by rlucente-retro** [comment]
Yeah, brew likes to install everything in /usr/local/bin on the mac which sometimes conflicts with things I copy there.
